### ISSUE TITLE
[Q&A]: is quarto-pyodide extension a subset of the quarto-live one?

### ISSUE THREAD

**Issue by Analect** [coatless-quarto/pyodide#24]
### What's your question?

Thanks for all your efforts with these tools.

I was also looking at https://r-wasm.github.io/quarto-live/ as well as the faq on this site at https://quarto.thecoatlessprofessor.com/pyodide/qpyodide-faq.html.

Am I right in thinking that this `quarto-pyodide` extension is purely focused on enabling python in the browser using wasm, where as the `quarto-live` one includes both R and python, and also includes some handling of utilities around exercises/grading and integration with OJS.

Is the direction of travel for the `quarto-pyodide` extension looking to solve different things?

**Comment by coatless** [comment]
@Analect `quarto-pyodide` came before the official WASM backend from `quarto-live`. 

Some key differences:

1. You can't talk back and forth between R, Python, and Observable.
   - You only get access to Pyodide. 
2. No code exercise checking is implemented.
3. Code cell uses Monaco Editor instead of Code Mirror.
4. `quarto-live` has official Posit support with one of their FTE assigned to it; `quarto-pyodide` is 100% community developed with no financial support.

**Comment by Analect** [comment]
Thanks @coatless for clarifying and thanks for all your efforts in bringing these technologies to the masses.
